import Config

port = String.to_integer(System.get_env("PORT") || "4000")

database_config =
  case {System.get_env("DATABASE_URL"), System.get_env("DATABASE_SOCKET_DIR")} do
    {database_url, _socket_dir} when database_url not in [nil, ""] ->
      [url: database_url]

    {_database_url, socket_dir} when socket_dir not in [nil, ""] ->
      [
        socket_dir: socket_dir,
        username: System.get_env("DATABASE_USERNAME") || "postgres",
        database: System.get_env("DATABASE_NAME") || "whiteboard_dev"
      ]

    _external_database ->
      [
        username: "postgres",
        password: "postgres",
        hostname: "localhost",
        database: "whiteboard_dev"
      ]
  end

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :whiteboard, Whiteboard.Repo, database_config

# Configure your database
config :whiteboard, Whiteboard.Repo,
  # For development, we disable any cache and enable
  # debugging and code reloading.
  #
  # The watchers configuration can be used to run external
  # watchers to your application. For example, we can use it
  # ## SSL Support
  stacktrace: true,
  # to bundle .js and .css sources.
  #
  # In order to use HTTPS in development, a self-signed
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :whiteboard, WhiteboardWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # certificate can be generated by running the following

  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # Mix task:
  #
  #     mix phx.gen.cert
  #
  # Run `mix help phx.gen.cert` for more information.
  #
  # The `http:` config above can be replaced with:
  #
  #     https: [
  #       port: 4001,
  #       cipher_suite: :strong,
  http: [ip: {0, 0, 0, 0}, port: port],
  check_origin: false,
  code_reloader: true,
  # Watch static and templates for browser reloading.
  #       keyfile: "priv/cert/selfsigned_key.pem",
  #       certfile: "priv/cert/selfsigned.pem"
  #     ],
  #
  # If desired, both `http:` and `https:` keys can be
  # configured to run both http and https servers on
  # different ports.
  debug_errors: true,
  secret_key_base: "npr3y/Lt8Ur5B8U5YJFc7EngH1SPEOj7HJxrmyJBRHElaoQaxk0ac2uuOXsEbKoi",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:whiteboard, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:whiteboard, ~w(--watch)]}
  ]

config :whiteboard, WhiteboardWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/whiteboard_web/(controllers|live|components)/.*(ex|heex)$",
      ~r"lib/whiteboard_web/router.ex$"
    ]
  ]

# Global settings
config :whiteboard, :base_url, "http://localhost:#{port}"

# Enable dev routes for dashboard and mailbox
config :whiteboard, dev_routes: true
